### ISSUE TITLE
Blumenrecherche

### ISSUE THREAD

**Issue by christingoeb** [christingoeb/flowwas#8]
- jeder 10 (50) Blumen raussuchen und ins Excel-Dokument

**Comment by Tina-Wahmkow** [comment]
haben ir gemacht, siehe [Excel](https://docs.google.com/spreadsheets/d/1c53GvYxzV85ryVCMl4wC5P1YUF2YTRc94aqhlOmsO_M/edit?gid=0#gid=0)
